name: Run Lottery Analysis

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch NJ lottery data
        run: |
          python src/fetch_nj_latest.py

      - name: Debug folders after fetch
        run: |
          echo "== LIST data directory =="
          ls -R data || true
          echo "== Current directory =="
          pwd

      - name: Analyze Powerball
        run: |
          python src/analyze_powerball.py

      - name: Analyze Mega Millions
        run: |
          python src/analyze_mega.py

      - name: Analyze Pick 6
        run: |
          python src/analyze_pick6.py
